# -*- coding: utf-8 -*-
"""Launch Countdown 1 Stuff

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ti9JJAWVFHdZXZLDdHU2BWdmXSXcM-Ff
"""

print("Hello world")

cupcakeType = "chocolate"
cupcakeOrderCount = 12
cupcakeFlour = 2.53
rottenEgg == False
cupcakeAddOn = ['sprinkles','bacon','strawberries']

for a in range(13):
  print("Number of cupcakes frosted: " + str(a))

if (rottenEgg == False):
  print("throw it out")
elif (rottenEgg == False):
  print("use that")
else:
  print("wheres the egg?")

#Guess the number
import random
number = random.randrange(0,50)
userGuess = -1
while userGuess != number:
  userGuess = int(input("Enter a number"))
  if userGuess < number:
    print("too low")
  if userGuess > number:
    print("too high")
  if userGuess ==  number:
    print("correct")
    break

#Rock Paper Scissors
import random

winlose = False
play = True
first = True
def showComputer(a):
  print("Computer chooses " + a)

def playFirst():
    global play
    playBool = str(input("Start? (y/n) "))
    if playBool == "n":
      play = False

def playAgain():
    playBool = str(input("Play Again? (y/n) "))
    global play
    if playBool == "n":
      play = False

while winlose == False and play == True:
  print("")
  if first == True:
    playFirst()
    first = False
  elif first == False:
    playAgain()
  if play == False:
    break
  print("")
  choice = input("Enter 'rock', 'paper', or 'scissors' here: ")
  rps = ["rock", "paper", "scissors"]
  computerChoice = random.choice(rps)
  showComputer(computerChoice)
  first = False
  if choice == computerChoice:
    print("Tie!")
  if choice == "rock" and computerChoice == "scissors":
    print("You win")
    winlose = True
  if choice == "rock" and computerChoice == "paper":
    print("You lose")
  if choice == "paper" and computerChoice == "rock":
    print("You win")
    winlose = True
  if choice == "paper" and computerChoice == "scissors":
    print("You lose")
  if choice == "scissors" and computerChoice == "paper":
    print("You win")
    winlose = True
  if choice == "scissors" and computerChoice == "rock":
    print("You lose")

x = 5
def a():
  x